// Code generated by girgen. DO NOT EDIT.

package gtklayershell

import (
	_ "runtime/cgo"
)

// #cgo pkg-config: gtk-layer-shell-0 gtk+-3.0
// #cgo CFLAGS: -Wno-deprecated-declarations
// #include <stdlib.h>
// #include <gtk-layer-shell/gtk-layer-shell.h>
import "C"
